sudo: false
language: android
jdk: oraclejdk8

before_script:
  - cd AndroidApp-DrinkIT/

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.1
    - android-28
  licenses:
    - '.+'

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_EMULATOR_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=28.0.1
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20

before_install:
  - yes | sdkmanager "platforms;android-28"


script:
  - ./gradlew 
