language: android

before_script: cd AndroidApp-DrinkIT

android:
  components:
    - build-tools-26.0.2
    - android-26
  licences:
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-26"
