language: android

before_script: cd AndroidApp-DrinkIT

android:
  components:
    - build-tools-28.0.2
    - android-28
  licences:
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-28"
